package main

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// The Go arm of the cross-language capability conformance check.
//
// The supervisor writes the session table in Python; this component reads it. Two things have to
// agree across that boundary and nothing in either language forces them to:
//
//  1. the digest convention — SHA-256 over the PRESENTED HANDLE STRING as bytes, not over the
//     bytes the hex decodes to; and
//  2. the column names in the session table.
//
// Both failure modes are total: every request denied capability_not_honoured, with no partial
// signal to notice it by. This test reads a database written by the supervisor's own code
// (tests/fixtures/session_conformance.sqlite3, regenerated by
// `python tests/fixtures/session_conformance.py`) rather than one built here, so a change on
// either side breaks it.
//
// The Python counterpart is tests/unit/test_session_conformance.py.

type conformanceSession struct {
	SessionID        string  `json:"session_id"`
	Handle           string  `json:"handle"`
	State            string  `json:"state"`
	LeaseExpiresAt   float64 `json:"lease_expires_at"`
	HonouredAtNow    bool    `json:"honoured_at_now"`
	Why              string  `json:"why"`
	CapabilitySHA256 string  `json:"capability_sha256"`
}

type conformanceVectors struct {
	Now      float64              `json:"now"`
	Database string               `json:"database"`
	Sessions []conformanceSession `json:"sessions"`
}

const conformanceDir = "../../tests/fixtures"

func loadConformance(t *testing.T) (conformanceVectors, string) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(conformanceDir, "session_conformance.json"))
	if err != nil {
		t.Fatalf("conformance vectors unreadable, so this test covers nothing: %v", err)
	}
	var v conformanceVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("conformance vectors unparseable: %v", err)
	}
	if len(v.Sessions) == 0 {
		t.Fatal("conformance vectors are empty; a vacuous pass is not a pass")
	}
	return v, copyFixtureDB(t, filepath.Join(conformanceDir, v.Database))
}

// copyFixtureDB byte-copies the committed database into the test's temporary directory and
// returns the copy's path.
//
// **Not a convenience, and not a weakening of what these tests read.** The committed fixture is a
// WAL-mode database — finding 033 reads its header bytes 18/19 as 2,2 and treats that as a
// property, because the supervisor's own writer puts every store into WAL. SQLite requires the
// shared-memory index for a WAL database on EVERY connection including a `mode=ro` one, so
// `OpenSessionStore` on the committed path creates `session_conformance.sqlite3-shm` and `-wal`
// beside a tracked file and leaves them there. Two passes have now reported them as stray
// untracked files.
//
// A permanently dirty `git status` is not cosmetic in this repository: reading it for entries
// nobody created is the defence against staging something unintended, and constant noise erodes
// it. The alternatives were both worse. Gitignoring the pair hides any future creation of them,
// including one that is a real defect. Converting the fixture out of WAL would make it stop being
// byte-representative of what the supervisor produces, which is the whole of its value, and
// `tests/unit/test_session_conformance.py` asserts exactly that correspondence. Opening with
// `immutable=1` here would stop these tests exercising `OpenSessionStore`'s production DSN, which
// is the other half of what they are for.
//
// A copy changes none of that. The bytes are identical, the open is the production one, and the
// sidecars land in a directory the test framework removes.
func copyFixtureDB(t *testing.T, path string) string {
	t.Helper()
	bytes, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("the committed conformance database is unreadable, so this test covers "+
			"nothing: %v", err)
	}
	copied := filepath.Join(t.TempDir(), filepath.Base(path))
	if err := os.WriteFile(copied, bytes, 0o600); err != nil {
		t.Fatalf("cannot copy the conformance database: %v", err)
	}
	return copied
}

// TestDigestConventionMatchesTheSupervisor pins the half of the boundary that has no type to
// enforce it: both sides pass a hex string and neither can tell which convention produced it.
func TestDigestConventionMatchesTheSupervisor(t *testing.T) {
	vectors, _ := loadConformance(t)
	for _, s := range vectors.Sessions {
		if got := capabilityDigest(s.Handle); got != s.CapabilitySHA256 {
			t.Errorf("%s: capabilityDigest(handle) = %s, supervisor wrote %s\n"+
				"the two sides disagree about how a handle is digested; every request "+
				"would be denied capability_not_honoured", s.SessionID, got, s.CapabilitySHA256)
		}
	}
}

// TestSupervisorWrittenSessionTableIsReadable proves the schema agrees. It reads a database this
// package never wrote, with the production read-only store.
func TestSupervisorWrittenSessionTableIsReadable(t *testing.T) {
	vectors, dbPath := loadConformance(t)
	store, err := OpenSessionStore(dbPath)
	if err != nil {
		t.Fatalf("cannot open the supervisor-written database: %v", err)
	}
	defer store.Close()

	for _, s := range vectors.Sessions {
		row, err := store.LookupByCapability(context.Background(), s.CapabilitySHA256)
		if err != nil {
			t.Fatalf("%s: lookup failed against a supervisor-written table: %v\n"+
				"a column name has drifted", s.SessionID, err)
		}
		if row.SessionID != s.SessionID {
			t.Errorf("session_id = %q, want %q", row.SessionID, s.SessionID)
		}
		if row.State != s.State {
			t.Errorf("%s: state = %q, want %q", s.SessionID, row.State, s.State)
		}
		if row.LeaseExpiresAt != s.LeaseExpiresAt {
			t.Errorf("%s: lease_expires_at = %v, want %v",
				s.SessionID, row.LeaseExpiresAt, s.LeaseExpiresAt)
		}
	}
}

// TestStageOneAgreesWithTheSupervisorsPredicate runs the real stage against the real fixture at
// the instant the fixture records, and compares its allow/deny to the supervisor's own
// `SessionRow.honoured_at`. This is the assertion that would have caught a disagreement about what
// STARTING means, or about whether a lease boundary is inclusive.
func TestStageOneAgreesWithTheSupervisorsPredicate(t *testing.T) {
	vectors, dbPath := loadConformance(t)
	store, err := OpenSessionStore(dbPath)
	if err != nil {
		t.Fatalf("cannot open the supervisor-written database: %v", err)
	}
	defer store.Close()

	sec := int64(vectors.Now)
	nsec := int64((vectors.Now - float64(sec)) * 1e9)
	at := func() time.Time { return time.Unix(sec, nsec) }
	stage := NewCapabilityStage(store, at)

	for _, s := range vectors.Sessions {
		t.Run(s.SessionID, func(t *testing.T) {
			res, err := stage.Evaluate(context.Background(), capabilityRequest(s.Handle))
			if err != nil {
				t.Fatalf("stage returned an error: %v", err)
			}
			if res.allowed != s.HonouredAtNow {
				t.Fatalf("stage allowed = %v, supervisor honoured_at = %v (rule %q)\n%s",
					res.allowed, s.HonouredAtNow, res.ruleID, s.Why)
			}
			if !res.allowed && !knownRule(res.ruleID) {
				t.Fatalf("denied with unregistered rule id %q", res.ruleID)
			}
		})
	}
}

// TestTerminatedSessionWithLiveLeaseIsDenied is the SC-024 replay shape, stated separately because
// it is the one row where the lease alone would say yes. A stage that checked only expiry would
// pass every other row in this fixture.
func TestTerminatedSessionWithLiveLeaseIsDenied(t *testing.T) {
	vectors, dbPath := loadConformance(t)
	store, err := OpenSessionStore(dbPath)
	if err != nil {
		t.Fatalf("cannot open the supervisor-written database: %v", err)
	}
	defer store.Close()

	sec := int64(vectors.Now)
	nsec := int64((vectors.Now - float64(sec)) * 1e9)
	stage := NewCapabilityStage(store, func() time.Time { return time.Unix(sec, nsec) })

	var found bool
	for _, s := range vectors.Sessions {
		// The lease is read from the DATABASE, not from the vector's claim about it.
		// Reading it from the JSON is what let the first version of this test pass while
		// covering nothing: the vector said the lease was live, the database said zero.
		row, err := store.LookupByCapability(context.Background(), s.CapabilitySHA256)
		if err != nil {
			t.Fatalf("%s: lookup failed: %v", s.SessionID, err)
		}
		if row.State != sessionStateTerminated || row.LeaseExpiresAt <= vectors.Now {
			continue
		}
		found = true

		res, err := stage.Evaluate(context.Background(), capabilityRequest(s.Handle))
		if err != nil {
			t.Fatalf("%s: stage returned an error: %v", s.SessionID, err)
		}
		if res.allowed {
			t.Fatalf("%s: a TERMINATED session with a lease valid until %v was honoured "+
				"at %v. The state check is not independent of the expiry check.",
				s.SessionID, row.LeaseExpiresAt, vectors.Now)
		}
	}
	if !found {
		t.Fatal("no session in the fixture is TERMINATED with a lease that is still live, " +
			"so nothing here distinguishes the state check from the expiry check. " +
			"The supervisor's terminate() zeroes the lease, which is why the fixture " +
			"writes this row directly — if that row is gone, this test covers nothing.")
	}
}
